#  Partie 1: Récupération des données

Ce notebook à pour but de récupérer les données issues de la base de donnée du gouvernement de recencement des transactions immobilières, dans le cadre du projet "infrastructure de recharge" 

Les données ont été préalablement téléchargées au format csv depuis le site officiel du gouvernement et nommés selon la règle suivante:

YYYY_XX.csv où YYYY corresponds à l'année en 4 chiffres et XX corresponds au numéro de département.

In [2]:
#Importation des fichiers csv:
import pandas as pd

idf2019_75=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_75.csv")
idf2019_77=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_77.csv")
idf2019_78=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_78.csv")
idf2019_91=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_91.csv")
idf2019_92=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_92.csv")
idf2019_93=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_93.csv")
idf2019_94=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_94.csv")
idf2019_95=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_95.csv")

C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\2121278549.py:4: DtypeWarning: Columns (18,20,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2019_75=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_75.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\2121278549.py:5: DtypeWarning: Columns (14,16) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2019_77=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_77.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\2121278549.py:6: DtypeWarning: Columns (14,16,18) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2019_78=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_78.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\2121278549.py:7: DtypeWarning: Columns (14,16) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2019_91=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_91.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\2121278549.py:8: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2019_92=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2019_92.csv")

In [3]:
idf2020_75=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_75.csv")
idf2020_77=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_77.csv")
idf2020_78=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_78.csv")
idf2020_91=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_91.csv")
idf2020_92=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_92.csv")
idf2020_93=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_93.csv")
idf2020_94=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_94.csv")
idf2020_95=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_95.csv")

C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\3066558662.py:1: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2020_75=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_75.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\3066558662.py:2: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2020_77=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_77.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\3066558662.py:4: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2020_91=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_91.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\3066558662.py:6: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2020_93=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2020_93.csv")

In [4]:
idf2021_75=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_75.csv")
idf2021_77=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_77.csv")
idf2021_78=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_78.csv")
idf2021_91=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_91.csv")
idf2021_92=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_92.csv")
idf2021_93=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_93.csv")
idf2021_94=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_94.csv")
idf2021_95=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_95.csv")

C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\195595831.py:1: DtypeWarning: Columns (18,20,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2021_75=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_75.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\195595831.py:2: DtypeWarning: Columns (17,20) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2021_77=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_77.csv")
C:\Users\alaro\AppData\Local\Temp\ipykernel_24304\195595831.py:4: DtypeWarning: Columns (18,20,22,24) have mixed types. Specify dtype option on import or set low_memory=False.
  idf2021_91=pd.read_csv(r"C:\Users\alaro\Downloads\Dataset\2021_91.csv")

In [5]:
#Concaténation des dataframes créés en un seul dataframe:
df= pd.concat([idf2019_75, idf2019_77, idf2019_78, idf2019_91, idf2019_92, idf2019_93, idf2019_94, idf2019_95, 
              idf2020_75, idf2020_77, idf2020_78, idf2020_91, idf2020_92, idf2020_93, idf2020_94, idf2020_95, 
              idf2021_75, idf2021_77, idf2021_78, idf2021_91, idf2021_92, idf2021_93, idf2021_94, idf2021_95], axis=0)

df

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2019-1499564,2019-01-04,1,Vente,1196000.0,17.0,NaN,RUE DUPHOT,2999,75001.0,...,Appartement,112.0,3.0,NaN,NaN,NaN,NaN,NaN,2.325288,48.868416
1,2019-1499565,2019-01-03,1,Vente,1570490.0,13.0,NaN,RUE DE THORIGNY,9298,75003.0,...,Appartement,104.0,3.0,NaN,NaN,NaN,NaN,NaN,2.363076,48.860305
2,2019-1499565,2019-01-03,1,Vente,1570490.0,13.0,NaN,RUE DE THORIGNY,9298,75003.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.363076,48.860305
3,2019-1499566,2019-01-08,1,Vente,100000.0,1.0,NaN,RUE MAGELLAN,5903,75008.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.300028,48.869577
4,2019-1499567,2019-01-03,1,Vente,5400.0,79.0,NaN,RUE DES GRAVILLIERS,4302,75003.0,...,Appartement,21.0,1.0,NaN,NaN,NaN,NaN,NaN,2.353479,48.864674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22143,2021-484774,2021-03-03,1,Vente,10000.0,50.0,NaN,RUE DE CHANTEPUITS,0180,95220.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.163565,48.991762
22144,2021-484775,2021-03-10,1,Vente,165500.0,20.0,NaN,RUE DUGUAY,1830,95100.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.239818,48.938453
22145,2021-484775,2021-03-10,1,Vente,165500.0,20.0,NaN,RUE DUGUAY,1830,95100.0,...,Appartement,40.0,2.0,NaN,NaN,NaN,NaN,NaN,2.239818,48.938453
22146,2021-484776,2021-02-23,1,Vente,490000.0,16.0,NaN,RUE KLEBER,1070,95870.0,...,Maison,48.0,4.0,S,sols,NaN,NaN,135.0,2.213130,48.928280
22147,2021-484776,2021-02-23,1,Vente,490000.0,14.0,NaN,RUE KLEBER,1070,95870.0,...,Maison,48.0,4.0,S,sols,NaN,NaN,133.0,2.213223,48.928365

In [5]:
#Export du dataframe vers un format csv:
df.to_csv("IDF_2019_to_2021.csv", index=False)